### ISSUE TITLE
War1tool does not find video files because of case

### ISSUE THREAD

**Issue by baco** [Wargus/war1gus#108]
When running war1tool to extract data files ffmpeg command fails with error:

```
[concat @ 0x236d280] Impossible to open 'wc1/videos/HINTRO1.ogv'
wc1/videos/mylist.txt: No such file or directory
Can't concat intro videos. Is ffmpeg installed in PATH?
```

being wc1 the destination folder on an ext4 FS.

The hintro1.ogv file exists but is lower case. The FS distinguishes between upper and lower case.

ffmpeg is installed and in PATH, also are ffmpeg2theora and timidity.

**Comment by baco** [comment]
Filenames in `wc1/videos/mylist.txt` are written uppercase but the command line run by ffmpeg is outputting filenames lowercase.

**Comment by timfel** [comment]
Right now the case is decided based on the case of the data.war file. If that is all uppercase, the video files will be converted into all uppercase otherwise they are lowercase. However, there is additional step to mux the video and audio files for the intro sequences, and that did not honor the upper/lower flag. I just committed a potential fix.
