### ISSUE TITLE
double click on war1gus window title bar does not maximize

### ISSUE THREAD

**Issue by legluondunet** [Wargus/war1gus#129]
Hello,

when I double click on the war1gus window title bar, that does nothing,   this should maximize the window and the window content should be adapted (scaled?).

Thank you for your help.

**Comment by timfel** [comment]
With the default preferences in the latest nightly build, I'm setting war1gus into scaling mode (before it used to just show more of the map). With this the scaling now works, and you can resize the window. However, it only works if OpenGL mode works on your system (and since we use an old version of SDL, it might not)
