### ISSUE TITLE
Sunnyglade "Save Tower" bug, in Orc Campaign

### ISSUE THREAD

**Issue by Zombie-Ryushu** [Wargus/war1gus#169]
The Sunny Glade mission can't be completed due to the save tower requirements. If you save the tower, the scenario keeps going, if you destroy the tower, it ends in defeat

**Comment by Zombie-Ryushu** [comment]
You might need to make that Tower rescue-able.

**Comment by timfel** [comment]
It's fixed in master. The problem was that the roads counted as units for the player, and the victory condition was that the tower is the last remaining unit of the computer. that was never the case, because you cannot destroy the roads. There was actually a bug because the roads should have been neutral anyway, but the code to make them neutral had failed.
