### ISSUE TITLE
wargus components portable to install and use them without root rights

### ISSUE THREAD

**Issue by legluondunet** [Wargus/war1gus#191]
Hello,

is there already a way to make wargus components portable?
Do you plan to provide appimage?
The reasons I asked you this question: I plan to write Lutris scripts that could install automatically games (warcraft 1, starcraft etc...) with their appropriate wargus components. But for this I need portable executables (no need for root rights).

Thank you for your answer.

**Comment by legluondunet** [comment]
The reasons I asked you this question: I plan to write a Lutris script that could install automatically the game (warcraft 1, starcraft etc...) with wargus components. But for this I need portable executable (no need root rights).

**Comment by timfel** [comment]
There was a question about this for Windows. I don't have any plans to do it (because i would have to learn how and have limited time). There's no technical problem, you can make a self-contained folder with any stratagus game. If you or anyone else contributes the build scripts to do it, I'm happy to merge it.

**Comment by timfel** [comment]
Portable installer is now working and will be released as 3.1
